global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  insecure: true

ping: {}

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true

providers:
  docker:
    endpoint: "tcp://docker-proxy:2375"
    exposedByDefault: false
    network: public-net

  file:
    directory: /etc/traefik/dynamic
    watch: true
