global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  insecure: true # Dashboard available on :8080

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true

# Define other nodes as providers
providers:
  # Local docker instance
  docker-core:
    endpoint: "http://docker-proxy:2375" # 10.0.143.10:2375
    exposedByDefault: false

  docker-services:
    endpoint: "http://10.0.143.20:2375" # Services node
    exposedByDefault: false

  docker-games:
    endpoint: "http://10.0.143.30:2375" # Games node
    exposedByDefault: false

  # Dynamic file provider
  file:
    directory: /etc/traefik/dynamic
    watch: true
