version: 2
ethernets:
  eth0:
    dhcp4: false
    addresses:
      - {{IP}}/24
    routes:
      - to: default
        via: 10.0.143.1
    nameservers:
      addresses:
        - 1.1.1.1
        - 8.8.8.8
