services:
  traefik:
    image: traefik:latest
    container_name: traefik-core
    network_mode: host
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_APPDATA}/traefik:/etc/traefik # Main Configuration directory

  docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-proxy
    network_mode: host # Expose socket to host
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # --- Required for Traefik ---
      - CONTAINERS=1
      - EVENTS=1
      - VERSION=1
      - PINg=1
      # --- STRICT SECURITY ---
      - NETWORKS=0
      - SERVICES=0
      - SWARM=0
      - TASKS=0
      - VOLUMES=0
      - POSTS=0
      # --- ADDITIONAL ---
      - TZ=${TZ}

  cloudflare:
    image: cloudflare/cloudflared:latest
    pull_policy: always
    container_name: cloudflared
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run