global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  insecure: true # Dashboard available on :8080

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true

# Define other nodes as providers
providers:
  # Local docker instance
  docker:
    endpoint: "http://docker-proxy:2375"
    exposedByDefault: false

  # Dynamic file provider
  file:
    directory: /etc/traefik/dynamic
    watch: true
