services:
  traefik:
    image: traefik:latest
    container_name: traefik-core
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"     # HTTP
      - "81:8080"   # Traefik Dashboard
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_APPDATA}/traefik/dynamic:/etc/traefik/dynamic
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=http://docker-proxy:2375"
      - "--entrypoints.web.address=:80"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.forwardedHeaders.insecure=true"
      - "--log.level=DEBUG"
    networks:
      - core-mgmt

  cloudflare:
    image: cloudflare/cloudflared:latest
    pull_policy: always
    container_name: cloudflared
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - core-mgmt

networks:
  core-mgmt:
    name: core-mgmt-network
    external: true