services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - /mnt/root:/mnt/root:ro
      - ${PATH_STORAGE}:/mnt/storage:ro # Allows homepage to detect drive
      - ${PATH_APPDATA}/homepage:/app/config
      - ${PATH_LOGS}/homepage:/app/config/logs
    environment:
      HOMEPAGE_ALLOWED_HOSTS: dashboard.heldertheking.com
      PUID: ${PUID}
      PGID: ${PGID}
    networks:
      - core-mgmt

  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: always
    volumes:
      - ${PATH_APPDATA}/uptime-kuma:/app/data
    environment:
      - TZ=${TZ}
      - UMASK=0022
    networks:
      - core-mgmt
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://hc-ping.com/07c4cdb7-f2ea-4c76-835b-9128e40bd963" ]
      interval: 10m
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - WATCHTOWER_SCHEDULE=0 0 5 * * 6
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLL_BACK_ON_FAILURE=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=generic://${NOTIFY_URL}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
    networks:
      - core-mgmt

  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: https://monitoring.heldertheking.com
    volumes:
      - ${PATH_APPDATA}/beszel/hub:/beszel_data
      - ${BESZEL_SOCKET}:/beszel_socket
    networks:
      - core-mgmt

networks:
  core-mgmt:
    name: core-mgmt-network
    external: true