services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${PATH_APPDATA}/beszel-agent:/var/lib/beszel-agent
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: ${TZ}
      LISTEN: 45876
      HUB_URL: https://monitoring.${DOMAIN}
      TOKEN: ${BESZEL_TOKEN}
      KEY: ${BESZEL_KEY}

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PATH_APPDATA}/portainer:/data
    environment:
      TZ: ${TZ}
    networks:
      - base-net
      - public-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`containers.${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  base-net:
    name: base-net
    driver: bridge
  public-net:
    name: public-net
    external: true